import '../app/global.css'

export const metadata = {
  title: "TodoMate",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
          {/* <h1>Welcome! TodoMate</h1> */}
          {children}
      </body>
    </html>
  );
}
